import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'artifacts/desktop.png' });
  assert.equal(await page.locator('h1').count(), 1);
  await page.getByRole('button', { name: 'Pausar animación de la esfera' }).click();
  assert.equal(await page.getByRole('button', { name: 'Reanudar animación de la esfera' }).count(), 1);
  await page.getByRole('tab', { name: /Estado/ }).click();
  assert.match(await page.locator('#layer-panel').innerText(), /no registró estados/);
  await page.getByRole('tab', { name: /Adaptación/ }).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: /Expresión/ }).getAttribute('aria-selected'), 'true');
  await page.locator('#modelos').scrollIntoViewIfNeeded();
  await page.waitForTimeout(900);
  await page.screenshot({ path: 'artifacts/models.png' });
  await page.getByRole('button', { name: 'Agotado', exact: true }).click();
  await page.locator('#variation').fill('0');
  assert.match(await page.locator('.rhythm-value').innerText(), /310/);
  await page.getByRole('button', { name: 'Reproducir simulación' }).click();
  await page.waitForTimeout(1200);
  assert.ok((await page.locator('.rhythm-playback>p').innerText()).startsWith('No'));
  await page.getByRole('button', { name: 'Pausar simulación' }).click();
  await page.getByRole('button', { name: 'Explorar Referente humano' }).click();
  assert.match(await page.locator('.matrix-detail').innerText(), /REFERENCIA/);
  await page.locator('#laboratorio').scrollIntoViewIfNeeded();
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/laboratory.png' });
  await page.getByRole('button', { name: 'Observaciones', exact: true }).click();
  assert.equal(await page.locator('tbody tr').count(), 4);
  await page.getByRole('button', { name: 'Todos', exact: true }).click();
  assert.equal(await page.locator('tbody tr').count(), 10);
  await page.getByRole('button', { name: /Un fallo de contexto/ }).click();
  await page.locator('.model-tabs').getByRole('button', { name: 'Awly', exact: true }).click();
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  assert.match(await page.locator('.transcript-assistant p').innerText(), /wireframes/);
  await page.getByRole('button', { name: /Comprobación de memoria/ }).click();
  assert.match(await page.locator('.transcript-assistant p').innerText(), /12 minus 5 plus 9/);
  await page.getByRole('button', { name: /Flawly tiene emociones/ }).click();
  assert.equal(await page.getByRole('button', { name: /Flawly tiene emociones/ }).getAttribute('aria-expanded'), 'true');
  await page.locator('.nav-cta').click();
  await page.getByLabel('Tu nombre', { exact: true }).fill('Prueba Flawly');
  await page.getByLabel('Correo electrónico', { exact: true }).fill('prueba@example.com');
  await page.getByLabel(/Entiendo que Flawly/).check();
  await page.getByRole('button', { name: 'Preparar solicitud', exact: true }).click();
  assert.match(await page.locator('.prepared-state').innerText(), /no te inscribe/);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar mi solicitud' }).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'flawly-solicitud-de-interes.txt');
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal((await page.request.get('http://localhost:5173/docs/about-flawly.txt')).status(), 200);
  for (const width of [1440, 1024, 768, 600, 390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.waitForTimeout(350);
    const size = await page.evaluate(() => document.body.scrollWidth);
    console.log(`Viewport ${width}: page width ${size}`);
    if (size > width) console.log('Overflow elements:', await page.evaluate(() => [...document.querySelectorAll('body *')].filter(el => el.getBoundingClientRect().right > innerWidth + 2).map(el => ({ tag: el.tagName, class: el.className, right: el.getBoundingClientRect().right })).slice(0, 15)));
    assert.ok(size <= width, `Horizontal overflow at ${width}`);
    if (width === 390) await page.screenshot({ path: 'artifacts/mobile.png' });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Abrir menú' }).click();
  await page.locator('#main-nav').getByRole('link', { name: 'Modelos', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Abrir menú' }).getAttribute('aria-expanded'), 'false');
  assert.deepEqual(errors, []);
  console.log('PASS: architecture, keyboard, rhythm, matrix, filters, transcripts, FAQ, download, source, mobile menu, responsive widths. No JavaScript errors.');
} finally { await browser.close(); }
